# Generated by Django 5.1.5 on 2025-01-27 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodaskerapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL),
        ),
    ]
