# Generated by Django 5.1.5 on 2025-01-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodaskerapp', '0003_alter_restaurant_address_alter_restaurant_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Menu', to='foodaskerapp.restaurant')),
            ],
        ),
    ]
