# Generated by Django 5.1.5 on 2025-01-29 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodaskerapp', '0004_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='Restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MenuItem', to='foodaskerapp.restaurant'),
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=100)),
                ('customeremail', models.EmailField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('MenuItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderDetails', to='foodaskerapp.menuitem')),
            ],
        ),
    ]
